nicodes/nicodes/urls.py
from django.contrib import admin
from django.urls import path, include
from projects_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('projects_app.urls')),
]

nicodes/projects_app/urls.py
from django.contrib import admin
from django.urls import path
from projects_app import views


app_name = 'projects_app'

urlpatterns = [
    path('', views.projects, name='projects'),
]

nicodes/projects_app/models.py
from django.db import models

# Create your models here.

class Projects(models.Model):
    name = models.CharField(max_length=240)
    description = models.CharField(max_length=240)
    project_url = models.URLField(blank=True)

nicodes/projects_app/views.py
from django.shortcuts import render
from .models import Projects
# Create your views here.

def index(request):

    return render(request,'projects_app/index.html')

def projects(request):
    #need to create a list with all the projects

    projects_list = Projects.objects.order_by()  # creates a list of objects

    my_projects= {
        'projects':projects_list
        }

    return render(request,'projects_app/projects.html', context=my_projects)

nicodes/templates/projects_app/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Nicolas Ojeda</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'js/main.js' %}">

</head>
<body>
  <div class="container">
        <div class="row">
    <div class="col-2">
    </div>
    <div class="col-8">
        {% block body_block %}
        <!-- Everything outside this block will be inherited if you extend in another page -->

      {% endblock %}
    </div>
    <div class="col-2">
    </div>
  </div>
      <script src="{% static 'js/main.js' %}"></script>
</body>
</html>

nicodes/templates/projects_app/index.html
<!DOCTYPE html>
{% extends "projects_app/base.html" %}
{% block body_block %}


<h1>Welcome to the Home Page</h1>
<a href="{% url 'projects_app:projects' %}">View My Projects</a>

{% endblock %}

nicodes/templates/projects_app/projects.html
<!DOCTYPE html>
{% extends "projects_app/base.html" %}
{% block body_block %}

<div class="header">
    <h3><span class="username">nicolasOjeda</span><span class="directory">@CSULA$</span><span class="typed-text">ls projects</span><span class="cursor">&nbsp;</span></h3>
</div>

<div class="links">
    <a href="https://www.linkedin.com/in/nojeda3/">linkedin</a>
    <a href="https://github.com/nicocoa10">github</a>
<!--    <a href="http://goo.gl/Foy2Nc">resume</a>-->
    <a href="mailto:nicolas.ojeda71@gmail.com">email</a>
    <a href="https://www.dropbox.com/sh/edzcg1uxrc1tfxx/AAAM2KiYnUAmro3xI-12istja?dl=0">music</a>
  </div>
<div class="typed-text">
    <p>Welcome to my Projects Page</p>

</div>

<div class="changelog" >
    <h4 >Changelog</h4>
    <p>Check out what i been working on</p>

    <div >
        {% if projects %}
        <table class="table table-bordered"   >
            <thead>
            <tr>
                <th>Name</th><th>Decription</th><th>link</th>
            </tr>
            </thead>
            <tbody>
            {% for p in projects %}
            <tr>
                <td> {{ p.name }}</td>
                <td> {{ p.description }}</td>
                <td> <a href="{{ p.project_url }}">{{ p.project_url }} </a></td>
            </tr>
            </tbody>
            {% endfor %}
        </table>
        {% else %}
        <p>No Data to Display</p>
        {% endif %}


    </div>


</div>
{% endblock %}